### ISSUE TITLE
Best example so far.

### ISSUE THREAD

**Issue by ea7kir** [Hupka/swift-websocket-server#1]
Hi, and thanks for creating the best example Iv'e been able to find.  It compiles and runs on macOS, but unfortunatley not on Linux.  On the iMac, and using an app called Socket Debugger, sending `{"client":"C13C2DA8-13FA-4BA6-A361-61488AC5B66A","data":{"connect":true}}` only returns a `pong`.  I'm hoping you'll consider Linux and and implementing WSS secure sockets.  Looking through the code, I can't find a way to customise the host address and port, because on Linux I would need it to run on `0.0,0,0` and a port of my choice.   Do keep up the good work.

**Comment by Hupka** [comment]
Hi! 

Thank you your kind words!

I had trouble using any of the WebSocket debug tools out there. They always only work in certain conditions and don't really tell you what's off. I can recommend the CLI tool [`websocat`](https://github.com/vi/websocat). 

My guess would be that you are not sending the JSON binary encoded. The `-b` flag in the `websocat` call does this. 

About configuring the webserver: since it is a plain Vapor 4.0 webserver, you can follow the docs here: https://docs.vapor.codes/4.0/server/. Just add the corresponding config fields to the [configure.swift](https://github.com/Hupka/swift-websocket-server/blob/main/Sources/App/configure.swift) file. 

Unfortunately, I am not going to continue to expand this example. With regards to Linux this app _should_ compile as both, Vapor and Swift, should compile on Linux.

**Comment by ea7kir** [comment]
Very nice of you to respond.

I’ve been asking the Vapor team to publish some example code for Vapor and WebSocket-Kit for months, but nothing yet.  I’ve been going round in circles for almost a year with SwiftNIO and now the same with Vapor.  I wish developers would learn that it’s best to write the docs before writing the code.

Regards,
Michael Naylor - EA7KIR
https://michaelnaylor.es
